#!/usr/bin/env python3
"""Convert the iOS Localizable.strings files into Android strings.xml files.

Usage: python3 scripts/ios-strings-to-android.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
IOS_DIR = ROOT / "source/kana/kana"
RES_DIR = ROOT / "source/android/app/src/main/res"

LANGUAGES = {
    "en": "values",
    "ja": "values-ja",
    "zh-Hans": "values-b+zh+Hans",
    "zh-Hant": "values-b+zh+Hant",
    "ko": "values-ko",
    "de": "values-de",
    "fr": "values-fr",
    "es": "values-es",
}

# Android-specific wording; keyed by Android key, then iOS language.
OVERRIDES = {
    "restore_none_message": {
        "en": "No previous purchase was found for this Google account.",
        "ja": "この Google アカウントでの購入は見つかりませんでした。",
        "zh-Hans": "这个 Google 账号下没有找到之前的购买记录。",
        "zh-Hant": "這個 Google 帳戶下沒有找到先前的購買記錄。",
        "ko": "이 Google 계정에서 이전 구매를 찾을 수 없습니다.",
        "de": "Für dieses Google-Konto wurde kein früherer Kauf gefunden.",
        "fr": "Aucun achat précédent n'a été trouvé pour ce compte Google.",
        "es": "No se encontró ninguna compra anterior para esta cuenta de Google.",
    },
}

ADDITIONAL_STRINGS = {
    "privacy_policy": {
        "en": "Privacy policy",
        "ja": "プライバシーポリシー",
        "zh-Hans": "隐私政策",
        "zh-Hant": "隱私權政策",
        "ko": "개인정보처리방침",
        "de": "Datenschutzerklärung",
        "fr": "Politique de confidentialité",
        "es": "Política de privacidad",
    },
}

ENTRY = re.compile(r'^"([^"]+)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;')


def snake(key: str) -> str:
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", key).lower()


def parse(path: pathlib.Path) -> list[tuple[str, str]]:
    entries = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ENTRY.match(line.strip())
        if match:
            entries.append((match.group(1), match.group(2)))
    return entries


def to_android(value: str) -> str:
    value = value.replace("%@", "%1$s").replace("%d", "%1$d")
    value = value.replace('\\"', '"')
    value = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    value = value.replace("'", "\\'").replace('"', '\\"')
    return value


def render(language: str, entries: list[tuple[str, str]]) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- Generated by scripts/ios-strings-to-android.py from source/kana/kana/{language}.lproj/Localizable.strings. Do not edit by hand. -->",
        "<resources>",
    ]
    if language == "en":
        lines.append('    <string name="app_name" translatable="false">Kana</string>')
    for key, value in entries:
        name = snake(key)
        text = OVERRIDES.get(name, {}).get(language)
        text = to_android(text) if text is not None else to_android(value)
        lines.append(f'    <string name="{name}">{text}</string>')
    for name, translations in ADDITIONAL_STRINGS.items():
        lines.append(f'    <string name="{name}">{to_android(translations[language])}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def main() -> None:
    for language, folder in LANGUAGES.items():
        entries = parse(IOS_DIR / f"{language}.lproj" / "Localizable.strings")
        if len(entries) != 39:
            raise SystemExit(f"{language}: expected 39 strings, found {len(entries)}")
        target = RES_DIR / folder / "strings.xml"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(language, entries), encoding="utf-8")
        print(f"wrote {target.relative_to(ROOT)} ({len(entries) + len(ADDITIONAL_STRINGS)} strings)")


if __name__ == "__main__":
    main()
